### ISSUE TITLE
「各ターンの出力」のフォーマットが冗長

### ISSUE THREAD

**Issue by irxground** [exKAZUu/AIChallenge2018AtCodeFestival#22]
アタックフェーズのルールには以下のようにある
> すべて同じ正整数で、かつ、総和が 2X+1 の正整数を置きます。 例えば、メインフェーズで 2 回マージした場合、 1 個の 8、2 個の 4、3 個の 2 のいずれかのパターンで正整数を置かなければなりません。

一方、各ターンの出力は以下のように説明されている
> vi: i 個目の数 2<sup>vi</sup>を表す値

viはすべて同じ正の整数でなくていいけないので、出力は一回でよいのではないだろうか

**Comment by exKAZUu** [comment]
確かに、冗長ですね。（ルール初期案では `4 2 2` のような配置を許していたので、今のような記述になっていました・・。）
