### ISSUE TITLE
アタックフェーズにおける数の配置

### ISSUE THREAD

**Issue by Aquarius256** [exKAZUu/AIChallenge2018AtCodeFestival#24]
GitHub に不慣れですが失礼いたします。
アタックフェーズにおいて配置する数について1つ疑問があります。

ルールによれば、
「マージが発生した回数が X のとき、総和が 2^(X + 1) の正整数を置かなければならない」
となっていますが、そのあとに以下のような例が挙げられています。
「メインフェーズで 2 回マージした場合、 1 個の 8、2 個の 4、3 個の 2 のいずれかのパターンで正整数を置かなければなりません」

これはルールに従うと「'4' 個の 2」となるべきではないでしょうか。

それとも、以下を意図しているでしょうか？
「マージ回数が X のとき、正整数 2^Y (1 <= Y <= X + 1)を置くことができるが、
その場合ちょうど X - Y + 2 個置かなければならない」

**Comment by Aquarius256** [comment]
ご確認ありがとうございます。どうやらすでに改定のリクエストがなされていたようですね。失礼いたしました。

**Comment by exKAZUu** [comment]
@Aquarius256  いえいえ、ご報告感謝申し上げます。無事、Web上のルールも更新できたので、本件クローズいたします。
