### ISSUE TITLE
メインフェーズでのスコア

### ISSUE THREAD

**Issue by semiexp** [exKAZUu/AIChallenge2018AtCodeFestival#26]
> ターンプレイヤーは上下左右のいずれかの向きを 1 個選択します。 ボード上の数たちは、選択された向きに、ボードの端か他の数にぶつかるまで移動します。 このとき 2 個の等しい数がぶつかると、それらがマージ（加算）されて 1 個の数になります。 マージが発生するたび、マージによってできた数に等しい値がスコアに加算されます。

とありますが，

> 2 人のプレイヤーはそれぞれ 5 x 5 のサイズのボードと 0 のスコアを持っています

の通り，ボードとスコアは各プレイヤーごとに存在します．
数の移動は，両者のボードに対して同じ向きで発生するのでしょうか？それとも，自分のボードのみに発生するのでしょうか？

**Comment by exKAZUu** [comment]
@semiexp ご質問ありがとうございます！数の移動は自分のボードのみに発生します。その旨が分かるようにルールを更新いたします。
