### ISSUE TITLE
行と列の値域について

### ISSUE THREAD

**Issue by irxground** [exKAZUu/AIChallenge2018AtCodeFestival#31]
> r: ゲーム開始時に相手のボードに 2 を置く行
> c: ゲーム開始時に相手のノードに 2 を置く列
> ri: i 個目の数を置く行
> ci: i 個目の数を置く列

ボードのサイズは 5 x 5 とありますが、これらの値の範囲はは `0 <= r,c < 5` でしょうか？ それとも ` 1 <= r,c <= 5` でしょうか。

**Comment by exKAZUu** [comment]
@irxground ご質問ありがとうございます！ `1 <= r,c <= 5` ですが、その旨を記載いたします。
