### ISSUE TITLE
AIへの入力項目について

### ISSUE THREAD

**Issue by ustimaw** [exKAZUu/AIChallenge2018AtCodeFestival#46]
システムから受け取ることができれば便利かと思うのですが、いかがでしょうか。
進行に必須ではないかと存じますので、もしお時間がありましたらご検討いただけると幸いです。
・現在のターン数
・残り時間
・両プレイヤーのスコア

**Comment by exKAZUu** [comment]
@ustimaw ご提案ありがとうございます！現在、修正中です。もうしばらくお待ち下さい。

**Comment by exKAZUu** [comment]
反映いたしました、ご提案ありがとうございました m(_ _)m
