### ISSUE TITLE
1000ターン経過時の勝敗

### ISSUE THREAD

**Issue by primenumber** [exKAZUu/AIChallenge2018AtCodeFestival#56]
1000ターン経過後のスコアによる勝敗決定の勝者が逆になっていませんか？

https://aichallenge.exkazuu.net/contests/1/battle_results/611

https://github.com/exKAZUu/AIChallenge2018AtCodeFestival/blob/093b9b2bf546ba2ffc2bdf672e7f8074cdbb707a/Battle2048/src/main/java/net/exkazuu/battle2048/game/Game.java#L120
score1>score2のとき0の反対（つまり1）を勝者にしているように見えます

**Comment by togatoga** [comment]
同じ現象が発生しています。
https://aichallenge.exkazuu.net/contests/1/battle_results/878

**Comment by exKAZUu** [comment]
@primenumber @togatoga ご報告ありがとうございます、ご指摘の通りでした。今晩中に修正・反映いたします。
