### ISSUE TITLE
1MB以上のファイルを提出しようとすると弾かれる

### ISSUE THREAD

**Issue by saharan** [exKAZUu/AIChallenge2018AtCodeFestival#61]
提出ファイルサイズの上限がTBDなので、こちらが1MB未満になる場合は問題ありません。

サイズ制限によって戦略が変わってくるので、首を長くしてサイズ決定をお待ちしております…！

**Comment by exKAZUu** [comment]
@saharan ご指摘ありがとうございます、1MB未満とさせてください。今からドキュメントも更新いたします。

**Comment by saharan** [comment]
@exKAZUu 了解しました。ご回答ありがとうございます。
