### ISSUE TITLE
対戦のマッチングを改善してほしい

### ISSUE THREAD

**Issue by kmyk** [exKAZUu/AIChallenge2018AtCodeFestival#69]
提出があった直後のAIは優先的に対戦を発生させ、またレートの近いAIと優先的にマッチングするようにしてほしいです。
現状ではランダムにふたつのAIを選んでマッチングをしているように見えますが、これではあまり意味がない対戦が多いです。

**Comment by exKAZUu** [comment]
@kmyk ご提案ありがとうございます。修正いたします！

**Comment by exKAZUu** [comment]
修正いたしました。

**Comment by kmyk** [comment]
ありがとうございます。改善されてるよう見えます。
