### ISSUE TITLE
viewerを改善してほしい

### ISSUE THREAD

**Issue by kmyk** [exKAZUu/AIChallenge2018AtCodeFestival#70]
-   点数を表示してほしい
-   持ち時間を表示してほしい
-   横幅がずれてるのを直してほしい
-   勝因/敗因を表示してほしい
-   対戦ログを表示してほしい

レポジトリは https://github.com/exKAZUu/GameViewerForAIChallenge2018AtCodeFestival にありますが、なぜかminifiedなjsしか置いてないのでこちらにissueを立てました。よろしくお願いします。

**Comment by exKAZUu** [comment]
@kmyk 全てではありませんが、修正いたしました！

**Comment by kmyk** [comment]
ありがとうございます。かなり使いやすくなっていました。
(しかし持ち時間の表示にはバグがあるように見えるので修正してほしいです。)

**Comment by exKAZUu** [comment]
@kmyk ありがとうございます、待ち時間の表示についても、先ほど修正しました(v1.0.2)！

**Comment by kmyk** [comment]
ありがとうございます。だいたい動いてます。

しかしまだバグはあり、戻るのボタンを押した場合の表示がなんだか怪しいです。ターンの表示も怪しい(同一ターンが3回発生したりする)ので元々あるバグかもしれません。特にあって困らされるバグではないですが一応報告しておきます。

**Comment by kmyk** [comment]
ターンをシークバーで移動したりすると、点数の表示がPLAYER 0とPLAYER 1で逆になったりします。これは致命的なので直してほしいです

**Comment by exKAZUu** [comment]
@kmyk ご報告ありがとうございます。修正いたします！

**Comment by exKAZUu** [comment]
@kmyk 一通り修正が完了したので、クローズいたします！

**Comment by kmyk** [comment]
とても使いやすくなっていました。ありがとうございました。
