### ISSUE TITLE
対戦結果ページの表示改善

### ISSUE THREAD

**Issue by TumoiYorozu** [exKAZUu/AIChallenge2018AtCodeFestival#74]
対戦結果ページ（https://aichallenge.exkazuu.net/contests/1#battle_results）にて、
長いAI名を使っていると「リプレイを確認」リンクがスクロールしないと見れなくなってしまうので、
AI名の長さ制限をHTML上で行うか、「リプレイを確認」リンクのレイアウトを改善してほしい。

**Comment by exKAZUu** [comment]
@TumoiYorozu ご報告ありがとうございます、これは困りますね・・・。対応いたします！

**Comment by exKAZUu** [comment]
@TumoiYorozu 修正いたしました！
