### ISSUE TITLE
ビジュアライザの速度バーのバグ

### ISSUE THREAD

**Issue by TumoiYorozu** [exKAZUu/AIChallenge2018AtCodeFestival#75]
ビジュアライザ https://www.exkazuu.net/GameViewerForAIChallenge2018AtCodeFestival/
にて、速度バーを操作してデフォルト以外の速度にした場合、MAX or それ以外で、超高速 or 低速 の2択速度でしかリプレイできていない気がする。
Windows 10 Chrome/Firefox で確認

**Comment by exKAZUu** [comment]
@TumoiYorozu ご報告ありがとうございました、修正いたしました！
